---
title: "git_01"
author: "Juliana Villa"
date: "28 May 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In depths of night where shadows roam,  
And whispers weave through darkened gloam,  
I stand upon life's shifting shore,  
With dreams that haunt, and hopes that soar.  

In chambers of the soul, I find,  
A labyrinth of thoughts entwined,  
Where passions rage and doubts doth dwell,  
Within this mortal shell.  

Yet in the midst of swirling storm,  
I feel a flicker, small, yet warm,  
A beacon bright amidst the gloom,  
A flame that burns beyond the tomb.  

For though this world be fraught with pain,  
And all our striving seems in vain,  
There lies within a sacred spark,  
A light that pierces through the dark.  

So let us seize this fleeting hour,  
And grasp the beauty, feel its power,  
For in this moment, here and now,  
We find the truth that we avow.  

Thus, let us live with all our might,  
Embrace the day, embrace the night,  
For in the end, when all is done,  
We'll find our rest, our victory won.  